import { ArrowRight, BookOpen } from 'lucide-react';
import { Link } from 'react-router-dom';

export function Help() {
  return <div className="page help-page"><header className="page__head"><div><p className="eyebrow">HELP & GUIDANCE</p><h2 className="page__title">Let’s take it one step at a time.</h2><p className="page__sub">Tidemark compares shipping documents and points out details that may need your attention.</p></div><BookOpen size={30} aria-hidden="true" /></header>
    <section className="panel"><div className="panel__body"><h3>How to check a document</h3><ol className="simple-steps"><li><span>1</span><div><strong>Open “Needs review”</strong><p>Choose “Start review” to assign a review to yourself. If another person is already working on it, their name is shown.</p></div></li><li><span>2</span><div><strong>Compare the highlighted details</strong><p>The shipping instruction contains the requested details. The draft bill of lading is the document being checked. On a small screen, use the Documents and Your checks tabs to switch between them.</p></div></li><li><span>3</span><div><strong>Confirm or correct each value</strong><p>Choose “Confirm” if the suggested value is right, “Correct” to change it, or “Mark missing” if the information is absent from the document. With a keyboard: J and K move between items, Enter confirms, E corrects, M marks missing.</p></div></li><li><span>4</span><div><strong>Save your review</strong><p>The save button becomes available after every item has a decision. Keep the page open until you save. You’ll see a confirmation when your decisions are recorded, with a button to open the next review. Ctrl+S (⌘S on a Mac) also saves.</p></div></li></ol><Link to="/review" className="btn btn--primary btn--md">Go to reviews <ArrowRight size={17} /></Link></div></section>
    <section className="panel"><header className="panel__head"><h3 className="panel__title">What do the results mean?</h3></header><dl className="help-definitions"><div><dt>No differences found</dt><dd>The details that were checked agree between the documents.</dd></div><div><dt>Differences found</dt><dd>Some details differ. Open the email to see which ones need attention.</dd></div><div><dt>Needs review</dt><dd>The system is unsure. A person needs to confirm or correct the details.</dd></div><div><dt>No comparison needed</dt><dd>This email is a different type of request, so its documents were not compared.</dd></div><div><dt>Could not finish</dt><dd>The check stopped. Open the email for the reason and instructions for trying again.</dd></div></dl></section>
    <section className="panel"><header className="panel__head"><h3 className="panel__title">Common questions</h3></header><div className="help-faq"><details><summary>What are SI and BL?</summary><p>SI means shipping instruction: the details requested for a shipment. BL means bill of lading: the shipping document checked against those instructions.</p></details><details><summary>What is an email import?</summary><p>An import is a group of emails brought into Tidemark together. “Email imports” shows how many arrived and whether any need another attempt.</p></details><details><summary>Why can’t I start a review?</summary><p>Your role may only allow you to view results. Reviewers and administrators can make decisions. A review already assigned to someone else should be completed by that person.</p></details><details><summary>How do I download results?</summary><p>Open “Download results” and choose “Spreadsheet (CSV)” for a file you can open in Excel. The file includes emails still waiting for review, so check the warning before downloading.</p></details></div></section>
  </div>;
}
